### ISSUE TITLE
Integrate React and Express

### ISSUE THREAD

**Issue by ifedyukin** [ifedyukin/Event-Listener#5]
@devAmoghS?

**Comment by ForsakenHarmony** [comment]
SSR?

**Comment by piq9117** [comment]
you want express to serve the react app? i think i can take this on. 😃

**Comment by devAmoghS** [comment]
@ifedyukin Let me know if i can be of some help in the future ?

**Comment by ifedyukin** [comment]
@devAmoghS ok 👍
